export { Hero } from './hero'
export { Features } from './features'
export { Pricing } from './pricing'
export { CTA } from './cta'
export { Header } from './header'
export { Footer } from './footer'
